# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/moerbius/Documents/GitHub/Diablo1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/moerbius/Documents/GitHub/Diablo1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/moerbius/Documents/GitHub/Diablo1/CMakeFiles /home/moerbius/Documents/GitHub/Diablo1//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/moerbius/Documents/GitHub/Diablo1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named diablo1

# Build rule for target.
diablo1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 diablo1
.PHONY : diablo1

# fast build rule for target.
diablo1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/build
.PHONY : diablo1/fast

src/audio/music.o: src/audio/music.cpp.o
.PHONY : src/audio/music.o

# target to build an object file
src/audio/music.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/audio/music.cpp.o
.PHONY : src/audio/music.cpp.o

src/audio/music.i: src/audio/music.cpp.i
.PHONY : src/audio/music.i

# target to preprocess a source file
src/audio/music.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/audio/music.cpp.i
.PHONY : src/audio/music.cpp.i

src/audio/music.s: src/audio/music.cpp.s
.PHONY : src/audio/music.s

# target to generate assembly for a file
src/audio/music.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/audio/music.cpp.s
.PHONY : src/audio/music.cpp.s

src/audio/sfx.o: src/audio/sfx.cpp.o
.PHONY : src/audio/sfx.o

# target to build an object file
src/audio/sfx.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/audio/sfx.cpp.o
.PHONY : src/audio/sfx.cpp.o

src/audio/sfx.i: src/audio/sfx.cpp.i
.PHONY : src/audio/sfx.i

# target to preprocess a source file
src/audio/sfx.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/audio/sfx.cpp.i
.PHONY : src/audio/sfx.cpp.i

src/audio/sfx.s: src/audio/sfx.cpp.s
.PHONY : src/audio/sfx.s

# target to generate assembly for a file
src/audio/sfx.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/audio/sfx.cpp.s
.PHONY : src/audio/sfx.cpp.s

src/focus_renderer.o: src/focus_renderer.cpp.o
.PHONY : src/focus_renderer.o

# target to build an object file
src/focus_renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/focus_renderer.cpp.o
.PHONY : src/focus_renderer.cpp.o

src/focus_renderer.i: src/focus_renderer.cpp.i
.PHONY : src/focus_renderer.i

# target to preprocess a source file
src/focus_renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/focus_renderer.cpp.i
.PHONY : src/focus_renderer.cpp.i

src/focus_renderer.s: src/focus_renderer.cpp.s
.PHONY : src/focus_renderer.s

# target to generate assembly for a file
src/focus_renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/focus_renderer.cpp.s
.PHONY : src/focus_renderer.cpp.s

src/font.o: src/font.cpp.o
.PHONY : src/font.o

# target to build an object file
src/font.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/font.cpp.o
.PHONY : src/font.cpp.o

src/font.i: src/font.cpp.i
.PHONY : src/font.i

# target to preprocess a source file
src/font.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/font.cpp.i
.PHONY : src/font.cpp.i

src/font.s: src/font.cpp.s
.PHONY : src/font.s

# target to generate assembly for a file
src/font.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/font.cpp.s
.PHONY : src/font.cpp.s

src/game.o: src/game.cpp.o
.PHONY : src/game.o

# target to build an object file
src/game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/game.cpp.o
.PHONY : src/game.cpp.o

src/game.i: src/game.cpp.i
.PHONY : src/game.i

# target to preprocess a source file
src/game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/game.cpp.i
.PHONY : src/game.cpp.i

src/game.s: src/game.cpp.s
.PHONY : src/game.s

# target to generate assembly for a file
src/game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/game.cpp.s
.PHONY : src/game.cpp.s

src/graphics/cel.o: src/graphics/cel.cpp.o
.PHONY : src/graphics/cel.o

# target to build an object file
src/graphics/cel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/graphics/cel.cpp.o
.PHONY : src/graphics/cel.cpp.o

src/graphics/cel.i: src/graphics/cel.cpp.i
.PHONY : src/graphics/cel.i

# target to preprocess a source file
src/graphics/cel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/graphics/cel.cpp.i
.PHONY : src/graphics/cel.cpp.i

src/graphics/cel.s: src/graphics/cel.cpp.s
.PHONY : src/graphics/cel.s

# target to generate assembly for a file
src/graphics/cel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/graphics/cel.cpp.s
.PHONY : src/graphics/cel.cpp.s

src/graphics/cel_animation.o: src/graphics/cel_animation.cpp.o
.PHONY : src/graphics/cel_animation.o

# target to build an object file
src/graphics/cel_animation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/graphics/cel_animation.cpp.o
.PHONY : src/graphics/cel_animation.cpp.o

src/graphics/cel_animation.i: src/graphics/cel_animation.cpp.i
.PHONY : src/graphics/cel_animation.i

# target to preprocess a source file
src/graphics/cel_animation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/graphics/cel_animation.cpp.i
.PHONY : src/graphics/cel_animation.cpp.i

src/graphics/cel_animation.s: src/graphics/cel_animation.cpp.s
.PHONY : src/graphics/cel_animation.s

# target to generate assembly for a file
src/graphics/cel_animation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/graphics/cel_animation.cpp.s
.PHONY : src/graphics/cel_animation.cpp.s

src/graphics/cl2.o: src/graphics/cl2.cpp.o
.PHONY : src/graphics/cl2.o

# target to build an object file
src/graphics/cl2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/graphics/cl2.cpp.o
.PHONY : src/graphics/cl2.cpp.o

src/graphics/cl2.i: src/graphics/cl2.cpp.i
.PHONY : src/graphics/cl2.i

# target to preprocess a source file
src/graphics/cl2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/graphics/cl2.cpp.i
.PHONY : src/graphics/cl2.cpp.i

src/graphics/cl2.s: src/graphics/cl2.cpp.s
.PHONY : src/graphics/cl2.s

# target to generate assembly for a file
src/graphics/cl2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/graphics/cl2.cpp.s
.PHONY : src/graphics/cl2.cpp.s

src/graphics/dun.o: src/graphics/dun.cpp.o
.PHONY : src/graphics/dun.o

# target to build an object file
src/graphics/dun.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/graphics/dun.cpp.o
.PHONY : src/graphics/dun.cpp.o

src/graphics/dun.i: src/graphics/dun.cpp.i
.PHONY : src/graphics/dun.i

# target to preprocess a source file
src/graphics/dun.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/graphics/dun.cpp.i
.PHONY : src/graphics/dun.cpp.i

src/graphics/dun.s: src/graphics/dun.cpp.s
.PHONY : src/graphics/dun.s

# target to generate assembly for a file
src/graphics/dun.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/graphics/dun.cpp.s
.PHONY : src/graphics/dun.cpp.s

src/graphics/min.o: src/graphics/min.cpp.o
.PHONY : src/graphics/min.o

# target to build an object file
src/graphics/min.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/graphics/min.cpp.o
.PHONY : src/graphics/min.cpp.o

src/graphics/min.i: src/graphics/min.cpp.i
.PHONY : src/graphics/min.i

# target to preprocess a source file
src/graphics/min.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/graphics/min.cpp.i
.PHONY : src/graphics/min.cpp.i

src/graphics/min.s: src/graphics/min.cpp.s
.PHONY : src/graphics/min.s

# target to generate assembly for a file
src/graphics/min.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/graphics/min.cpp.s
.PHONY : src/graphics/min.cpp.s

src/graphics/pal.o: src/graphics/pal.cpp.o
.PHONY : src/graphics/pal.o

# target to build an object file
src/graphics/pal.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/graphics/pal.cpp.o
.PHONY : src/graphics/pal.cpp.o

src/graphics/pal.i: src/graphics/pal.cpp.i
.PHONY : src/graphics/pal.i

# target to preprocess a source file
src/graphics/pal.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/graphics/pal.cpp.i
.PHONY : src/graphics/pal.cpp.i

src/graphics/pal.s: src/graphics/pal.cpp.s
.PHONY : src/graphics/pal.s

# target to generate assembly for a file
src/graphics/pal.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/graphics/pal.cpp.s
.PHONY : src/graphics/pal.cpp.s

src/graphics/til.o: src/graphics/til.cpp.o
.PHONY : src/graphics/til.o

# target to build an object file
src/graphics/til.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/graphics/til.cpp.o
.PHONY : src/graphics/til.cpp.o

src/graphics/til.i: src/graphics/til.cpp.i
.PHONY : src/graphics/til.i

# target to preprocess a source file
src/graphics/til.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/graphics/til.cpp.i
.PHONY : src/graphics/til.cpp.i

src/graphics/til.s: src/graphics/til.cpp.s
.PHONY : src/graphics/til.s

# target to generate assembly for a file
src/graphics/til.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/graphics/til.cpp.s
.PHONY : src/graphics/til.cpp.s

src/heroes/hero.o: src/heroes/hero.cpp.o
.PHONY : src/heroes/hero.o

# target to build an object file
src/heroes/hero.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/heroes/hero.cpp.o
.PHONY : src/heroes/hero.cpp.o

src/heroes/hero.i: src/heroes/hero.cpp.i
.PHONY : src/heroes/hero.i

# target to preprocess a source file
src/heroes/hero.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/heroes/hero.cpp.i
.PHONY : src/heroes/hero.cpp.i

src/heroes/hero.s: src/heroes/hero.cpp.s
.PHONY : src/heroes/hero.s

# target to generate assembly for a file
src/heroes/hero.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/heroes/hero.cpp.s
.PHONY : src/heroes/hero.cpp.s

src/heroes/rogue.o: src/heroes/rogue.cpp.o
.PHONY : src/heroes/rogue.o

# target to build an object file
src/heroes/rogue.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/heroes/rogue.cpp.o
.PHONY : src/heroes/rogue.cpp.o

src/heroes/rogue.i: src/heroes/rogue.cpp.i
.PHONY : src/heroes/rogue.i

# target to preprocess a source file
src/heroes/rogue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/heroes/rogue.cpp.i
.PHONY : src/heroes/rogue.cpp.i

src/heroes/rogue.s: src/heroes/rogue.cpp.s
.PHONY : src/heroes/rogue.s

# target to generate assembly for a file
src/heroes/rogue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/heroes/rogue.cpp.s
.PHONY : src/heroes/rogue.cpp.s

src/heroes/sorcerer.o: src/heroes/sorcerer.cpp.o
.PHONY : src/heroes/sorcerer.o

# target to build an object file
src/heroes/sorcerer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/heroes/sorcerer.cpp.o
.PHONY : src/heroes/sorcerer.cpp.o

src/heroes/sorcerer.i: src/heroes/sorcerer.cpp.i
.PHONY : src/heroes/sorcerer.i

# target to preprocess a source file
src/heroes/sorcerer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/heroes/sorcerer.cpp.i
.PHONY : src/heroes/sorcerer.cpp.i

src/heroes/sorcerer.s: src/heroes/sorcerer.cpp.s
.PHONY : src/heroes/sorcerer.s

# target to generate assembly for a file
src/heroes/sorcerer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/heroes/sorcerer.cpp.s
.PHONY : src/heroes/sorcerer.cpp.s

src/heroes/warrior.o: src/heroes/warrior.cpp.o
.PHONY : src/heroes/warrior.o

# target to build an object file
src/heroes/warrior.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/heroes/warrior.cpp.o
.PHONY : src/heroes/warrior.cpp.o

src/heroes/warrior.i: src/heroes/warrior.cpp.i
.PHONY : src/heroes/warrior.i

# target to preprocess a source file
src/heroes/warrior.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/heroes/warrior.cpp.i
.PHONY : src/heroes/warrior.cpp.i

src/heroes/warrior.s: src/heroes/warrior.cpp.s
.PHONY : src/heroes/warrior.s

# target to generate assembly for a file
src/heroes/warrior.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/heroes/warrior.cpp.s
.PHONY : src/heroes/warrior.cpp.s

src/logo_renderer.o: src/logo_renderer.cpp.o
.PHONY : src/logo_renderer.o

# target to build an object file
src/logo_renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/logo_renderer.cpp.o
.PHONY : src/logo_renderer.cpp.o

src/logo_renderer.i: src/logo_renderer.cpp.i
.PHONY : src/logo_renderer.i

# target to preprocess a source file
src/logo_renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/logo_renderer.cpp.i
.PHONY : src/logo_renderer.cpp.i

src/logo_renderer.s: src/logo_renderer.cpp.s
.PHONY : src/logo_renderer.s

# target to generate assembly for a file
src/logo_renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/logo_renderer.cpp.s
.PHONY : src/logo_renderer.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/pcx.o: src/pcx.cpp.o
.PHONY : src/pcx.o

# target to build an object file
src/pcx.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/pcx.cpp.o
.PHONY : src/pcx.cpp.o

src/pcx.i: src/pcx.cpp.i
.PHONY : src/pcx.i

# target to preprocess a source file
src/pcx.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/pcx.cpp.i
.PHONY : src/pcx.cpp.i

src/pcx.s: src/pcx.cpp.s
.PHONY : src/pcx.s

# target to generate assembly for a file
src/pcx.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/pcx.cpp.s
.PHONY : src/pcx.cpp.s

src/portrait_renderer.o: src/portrait_renderer.cpp.o
.PHONY : src/portrait_renderer.o

# target to build an object file
src/portrait_renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/portrait_renderer.cpp.o
.PHONY : src/portrait_renderer.cpp.o

src/portrait_renderer.i: src/portrait_renderer.cpp.i
.PHONY : src/portrait_renderer.i

# target to preprocess a source file
src/portrait_renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/portrait_renderer.cpp.i
.PHONY : src/portrait_renderer.cpp.i

src/portrait_renderer.s: src/portrait_renderer.cpp.s
.PHONY : src/portrait_renderer.s

# target to generate assembly for a file
src/portrait_renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/portrait_renderer.cpp.s
.PHONY : src/portrait_renderer.cpp.s

src/savegame_reader.o: src/savegame_reader.cpp.o
.PHONY : src/savegame_reader.o

# target to build an object file
src/savegame_reader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/savegame_reader.cpp.o
.PHONY : src/savegame_reader.cpp.o

src/savegame_reader.i: src/savegame_reader.cpp.i
.PHONY : src/savegame_reader.i

# target to preprocess a source file
src/savegame_reader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/savegame_reader.cpp.i
.PHONY : src/savegame_reader.cpp.i

src/savegame_reader.s: src/savegame_reader.cpp.s
.PHONY : src/savegame_reader.s

# target to generate assembly for a file
src/savegame_reader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/savegame_reader.cpp.s
.PHONY : src/savegame_reader.cpp.s

src/smacker/libsmackerdec/BitReader.o: src/smacker/libsmackerdec/BitReader.cpp.o
.PHONY : src/smacker/libsmackerdec/BitReader.o

# target to build an object file
src/smacker/libsmackerdec/BitReader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/smacker/libsmackerdec/BitReader.cpp.o
.PHONY : src/smacker/libsmackerdec/BitReader.cpp.o

src/smacker/libsmackerdec/BitReader.i: src/smacker/libsmackerdec/BitReader.cpp.i
.PHONY : src/smacker/libsmackerdec/BitReader.i

# target to preprocess a source file
src/smacker/libsmackerdec/BitReader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/smacker/libsmackerdec/BitReader.cpp.i
.PHONY : src/smacker/libsmackerdec/BitReader.cpp.i

src/smacker/libsmackerdec/BitReader.s: src/smacker/libsmackerdec/BitReader.cpp.s
.PHONY : src/smacker/libsmackerdec/BitReader.s

# target to generate assembly for a file
src/smacker/libsmackerdec/BitReader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/smacker/libsmackerdec/BitReader.cpp.s
.PHONY : src/smacker/libsmackerdec/BitReader.cpp.s

src/smacker/libsmackerdec/FileStream.o: src/smacker/libsmackerdec/FileStream.cpp.o
.PHONY : src/smacker/libsmackerdec/FileStream.o

# target to build an object file
src/smacker/libsmackerdec/FileStream.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/smacker/libsmackerdec/FileStream.cpp.o
.PHONY : src/smacker/libsmackerdec/FileStream.cpp.o

src/smacker/libsmackerdec/FileStream.i: src/smacker/libsmackerdec/FileStream.cpp.i
.PHONY : src/smacker/libsmackerdec/FileStream.i

# target to preprocess a source file
src/smacker/libsmackerdec/FileStream.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/smacker/libsmackerdec/FileStream.cpp.i
.PHONY : src/smacker/libsmackerdec/FileStream.cpp.i

src/smacker/libsmackerdec/FileStream.s: src/smacker/libsmackerdec/FileStream.cpp.s
.PHONY : src/smacker/libsmackerdec/FileStream.s

# target to generate assembly for a file
src/smacker/libsmackerdec/FileStream.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/smacker/libsmackerdec/FileStream.cpp.s
.PHONY : src/smacker/libsmackerdec/FileStream.cpp.s

src/smacker/libsmackerdec/LogError.o: src/smacker/libsmackerdec/LogError.cpp.o
.PHONY : src/smacker/libsmackerdec/LogError.o

# target to build an object file
src/smacker/libsmackerdec/LogError.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/smacker/libsmackerdec/LogError.cpp.o
.PHONY : src/smacker/libsmackerdec/LogError.cpp.o

src/smacker/libsmackerdec/LogError.i: src/smacker/libsmackerdec/LogError.cpp.i
.PHONY : src/smacker/libsmackerdec/LogError.i

# target to preprocess a source file
src/smacker/libsmackerdec/LogError.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/smacker/libsmackerdec/LogError.cpp.i
.PHONY : src/smacker/libsmackerdec/LogError.cpp.i

src/smacker/libsmackerdec/LogError.s: src/smacker/libsmackerdec/LogError.cpp.s
.PHONY : src/smacker/libsmackerdec/LogError.s

# target to generate assembly for a file
src/smacker/libsmackerdec/LogError.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/smacker/libsmackerdec/LogError.cpp.s
.PHONY : src/smacker/libsmackerdec/LogError.cpp.s

src/smacker/libsmackerdec/SmackerDecoder.o: src/smacker/libsmackerdec/SmackerDecoder.cpp.o
.PHONY : src/smacker/libsmackerdec/SmackerDecoder.o

# target to build an object file
src/smacker/libsmackerdec/SmackerDecoder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/smacker/libsmackerdec/SmackerDecoder.cpp.o
.PHONY : src/smacker/libsmackerdec/SmackerDecoder.cpp.o

src/smacker/libsmackerdec/SmackerDecoder.i: src/smacker/libsmackerdec/SmackerDecoder.cpp.i
.PHONY : src/smacker/libsmackerdec/SmackerDecoder.i

# target to preprocess a source file
src/smacker/libsmackerdec/SmackerDecoder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/smacker/libsmackerdec/SmackerDecoder.cpp.i
.PHONY : src/smacker/libsmackerdec/SmackerDecoder.cpp.i

src/smacker/libsmackerdec/SmackerDecoder.s: src/smacker/libsmackerdec/SmackerDecoder.cpp.s
.PHONY : src/smacker/libsmackerdec/SmackerDecoder.s

# target to generate assembly for a file
src/smacker/libsmackerdec/SmackerDecoder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/smacker/libsmackerdec/SmackerDecoder.cpp.s
.PHONY : src/smacker/libsmackerdec/SmackerDecoder.cpp.s

src/smacker/libsmackker.o: src/smacker/libsmackker.cpp.o
.PHONY : src/smacker/libsmackker.o

# target to build an object file
src/smacker/libsmackker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/smacker/libsmackker.cpp.o
.PHONY : src/smacker/libsmackker.cpp.o

src/smacker/libsmackker.i: src/smacker/libsmackker.cpp.i
.PHONY : src/smacker/libsmackker.i

# target to preprocess a source file
src/smacker/libsmackker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/smacker/libsmackker.cpp.i
.PHONY : src/smacker/libsmackker.cpp.i

src/smacker/libsmackker.s: src/smacker/libsmackker.cpp.s
.PHONY : src/smacker/libsmackker.s

# target to generate assembly for a file
src/smacker/libsmackker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/smacker/libsmackker.cpp.s
.PHONY : src/smacker/libsmackker.cpp.s

src/smacker/pklib/explode.o: src/smacker/pklib/explode.c.o
.PHONY : src/smacker/pklib/explode.o

# target to build an object file
src/smacker/pklib/explode.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/smacker/pklib/explode.c.o
.PHONY : src/smacker/pklib/explode.c.o

src/smacker/pklib/explode.i: src/smacker/pklib/explode.c.i
.PHONY : src/smacker/pklib/explode.i

# target to preprocess a source file
src/smacker/pklib/explode.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/smacker/pklib/explode.c.i
.PHONY : src/smacker/pklib/explode.c.i

src/smacker/pklib/explode.s: src/smacker/pklib/explode.c.s
.PHONY : src/smacker/pklib/explode.s

# target to generate assembly for a file
src/smacker/pklib/explode.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/smacker/pklib/explode.c.s
.PHONY : src/smacker/pklib/explode.c.s

src/states/intro_state.o: src/states/intro_state.cpp.o
.PHONY : src/states/intro_state.o

# target to build an object file
src/states/intro_state.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/states/intro_state.cpp.o
.PHONY : src/states/intro_state.cpp.o

src/states/intro_state.i: src/states/intro_state.cpp.i
.PHONY : src/states/intro_state.i

# target to preprocess a source file
src/states/intro_state.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/states/intro_state.cpp.i
.PHONY : src/states/intro_state.cpp.i

src/states/intro_state.s: src/states/intro_state.cpp.s
.PHONY : src/states/intro_state.s

# target to generate assembly for a file
src/states/intro_state.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/states/intro_state.cpp.s
.PHONY : src/states/intro_state.cpp.s

src/states/main_menu_state.o: src/states/main_menu_state.cpp.o
.PHONY : src/states/main_menu_state.o

# target to build an object file
src/states/main_menu_state.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/states/main_menu_state.cpp.o
.PHONY : src/states/main_menu_state.cpp.o

src/states/main_menu_state.i: src/states/main_menu_state.cpp.i
.PHONY : src/states/main_menu_state.i

# target to preprocess a source file
src/states/main_menu_state.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/states/main_menu_state.cpp.i
.PHONY : src/states/main_menu_state.cpp.i

src/states/main_menu_state.s: src/states/main_menu_state.cpp.s
.PHONY : src/states/main_menu_state.s

# target to generate assembly for a file
src/states/main_menu_state.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/states/main_menu_state.cpp.s
.PHONY : src/states/main_menu_state.cpp.s

src/states/new_hero_state.o: src/states/new_hero_state.cpp.o
.PHONY : src/states/new_hero_state.o

# target to build an object file
src/states/new_hero_state.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/states/new_hero_state.cpp.o
.PHONY : src/states/new_hero_state.cpp.o

src/states/new_hero_state.i: src/states/new_hero_state.cpp.i
.PHONY : src/states/new_hero_state.i

# target to preprocess a source file
src/states/new_hero_state.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/states/new_hero_state.cpp.i
.PHONY : src/states/new_hero_state.cpp.i

src/states/new_hero_state.s: src/states/new_hero_state.cpp.s
.PHONY : src/states/new_hero_state.s

# target to generate assembly for a file
src/states/new_hero_state.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/states/new_hero_state.cpp.s
.PHONY : src/states/new_hero_state.cpp.s

src/states/playing_state.o: src/states/playing_state.cpp.o
.PHONY : src/states/playing_state.o

# target to build an object file
src/states/playing_state.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/states/playing_state.cpp.o
.PHONY : src/states/playing_state.cpp.o

src/states/playing_state.i: src/states/playing_state.cpp.i
.PHONY : src/states/playing_state.i

# target to preprocess a source file
src/states/playing_state.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/states/playing_state.cpp.i
.PHONY : src/states/playing_state.cpp.i

src/states/playing_state.s: src/states/playing_state.cpp.s
.PHONY : src/states/playing_state.s

# target to generate assembly for a file
src/states/playing_state.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/states/playing_state.cpp.s
.PHONY : src/states/playing_state.cpp.s

src/states/select_hero_state.o: src/states/select_hero_state.cpp.o
.PHONY : src/states/select_hero_state.o

# target to build an object file
src/states/select_hero_state.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/states/select_hero_state.cpp.o
.PHONY : src/states/select_hero_state.cpp.o

src/states/select_hero_state.i: src/states/select_hero_state.cpp.i
.PHONY : src/states/select_hero_state.i

# target to preprocess a source file
src/states/select_hero_state.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/states/select_hero_state.cpp.i
.PHONY : src/states/select_hero_state.cpp.i

src/states/select_hero_state.s: src/states/select_hero_state.cpp.s
.PHONY : src/states/select_hero_state.s

# target to generate assembly for a file
src/states/select_hero_state.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/states/select_hero_state.cpp.s
.PHONY : src/states/select_hero_state.cpp.s

src/states/show_savegame_state.o: src/states/show_savegame_state.cpp.o
.PHONY : src/states/show_savegame_state.o

# target to build an object file
src/states/show_savegame_state.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/states/show_savegame_state.cpp.o
.PHONY : src/states/show_savegame_state.cpp.o

src/states/show_savegame_state.i: src/states/show_savegame_state.cpp.i
.PHONY : src/states/show_savegame_state.i

# target to preprocess a source file
src/states/show_savegame_state.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/states/show_savegame_state.cpp.i
.PHONY : src/states/show_savegame_state.cpp.i

src/states/show_savegame_state.s: src/states/show_savegame_state.cpp.s
.PHONY : src/states/show_savegame_state.s

# target to generate assembly for a file
src/states/show_savegame_state.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/states/show_savegame_state.cpp.s
.PHONY : src/states/show_savegame_state.cpp.s

src/storm/stormlib.o: src/storm/stormlib.cpp.o
.PHONY : src/storm/stormlib.o

# target to build an object file
src/storm/stormlib.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/storm/stormlib.cpp.o
.PHONY : src/storm/stormlib.cpp.o

src/storm/stormlib.i: src/storm/stormlib.cpp.i
.PHONY : src/storm/stormlib.i

# target to preprocess a source file
src/storm/stormlib.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/storm/stormlib.cpp.i
.PHONY : src/storm/stormlib.cpp.i

src/storm/stormlib.s: src/storm/stormlib.cpp.s
.PHONY : src/storm/stormlib.s

# target to generate assembly for a file
src/storm/stormlib.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/storm/stormlib.cpp.s
.PHONY : src/storm/stormlib.cpp.s

src/video.o: src/video.cpp.o
.PHONY : src/video.o

# target to build an object file
src/video.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/video.cpp.o
.PHONY : src/video.cpp.o

src/video.i: src/video.cpp.i
.PHONY : src/video.i

# target to preprocess a source file
src/video.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/video.cpp.i
.PHONY : src/video.cpp.i

src/video.s: src/video.cpp.s
.PHONY : src/video.s

# target to generate assembly for a file
src/video.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diablo1.dir/build.make CMakeFiles/diablo1.dir/src/video.cpp.s
.PHONY : src/video.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... diablo1"
	@echo "... src/audio/music.o"
	@echo "... src/audio/music.i"
	@echo "... src/audio/music.s"
	@echo "... src/audio/sfx.o"
	@echo "... src/audio/sfx.i"
	@echo "... src/audio/sfx.s"
	@echo "... src/focus_renderer.o"
	@echo "... src/focus_renderer.i"
	@echo "... src/focus_renderer.s"
	@echo "... src/font.o"
	@echo "... src/font.i"
	@echo "... src/font.s"
	@echo "... src/game.o"
	@echo "... src/game.i"
	@echo "... src/game.s"
	@echo "... src/graphics/cel.o"
	@echo "... src/graphics/cel.i"
	@echo "... src/graphics/cel.s"
	@echo "... src/graphics/cel_animation.o"
	@echo "... src/graphics/cel_animation.i"
	@echo "... src/graphics/cel_animation.s"
	@echo "... src/graphics/cl2.o"
	@echo "... src/graphics/cl2.i"
	@echo "... src/graphics/cl2.s"
	@echo "... src/graphics/dun.o"
	@echo "... src/graphics/dun.i"
	@echo "... src/graphics/dun.s"
	@echo "... src/graphics/min.o"
	@echo "... src/graphics/min.i"
	@echo "... src/graphics/min.s"
	@echo "... src/graphics/pal.o"
	@echo "... src/graphics/pal.i"
	@echo "... src/graphics/pal.s"
	@echo "... src/graphics/til.o"
	@echo "... src/graphics/til.i"
	@echo "... src/graphics/til.s"
	@echo "... src/heroes/hero.o"
	@echo "... src/heroes/hero.i"
	@echo "... src/heroes/hero.s"
	@echo "... src/heroes/rogue.o"
	@echo "... src/heroes/rogue.i"
	@echo "... src/heroes/rogue.s"
	@echo "... src/heroes/sorcerer.o"
	@echo "... src/heroes/sorcerer.i"
	@echo "... src/heroes/sorcerer.s"
	@echo "... src/heroes/warrior.o"
	@echo "... src/heroes/warrior.i"
	@echo "... src/heroes/warrior.s"
	@echo "... src/logo_renderer.o"
	@echo "... src/logo_renderer.i"
	@echo "... src/logo_renderer.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/pcx.o"
	@echo "... src/pcx.i"
	@echo "... src/pcx.s"
	@echo "... src/portrait_renderer.o"
	@echo "... src/portrait_renderer.i"
	@echo "... src/portrait_renderer.s"
	@echo "... src/savegame_reader.o"
	@echo "... src/savegame_reader.i"
	@echo "... src/savegame_reader.s"
	@echo "... src/smacker/libsmackerdec/BitReader.o"
	@echo "... src/smacker/libsmackerdec/BitReader.i"
	@echo "... src/smacker/libsmackerdec/BitReader.s"
	@echo "... src/smacker/libsmackerdec/FileStream.o"
	@echo "... src/smacker/libsmackerdec/FileStream.i"
	@echo "... src/smacker/libsmackerdec/FileStream.s"
	@echo "... src/smacker/libsmackerdec/LogError.o"
	@echo "... src/smacker/libsmackerdec/LogError.i"
	@echo "... src/smacker/libsmackerdec/LogError.s"
	@echo "... src/smacker/libsmackerdec/SmackerDecoder.o"
	@echo "... src/smacker/libsmackerdec/SmackerDecoder.i"
	@echo "... src/smacker/libsmackerdec/SmackerDecoder.s"
	@echo "... src/smacker/libsmackker.o"
	@echo "... src/smacker/libsmackker.i"
	@echo "... src/smacker/libsmackker.s"
	@echo "... src/smacker/pklib/explode.o"
	@echo "... src/smacker/pklib/explode.i"
	@echo "... src/smacker/pklib/explode.s"
	@echo "... src/states/intro_state.o"
	@echo "... src/states/intro_state.i"
	@echo "... src/states/intro_state.s"
	@echo "... src/states/main_menu_state.o"
	@echo "... src/states/main_menu_state.i"
	@echo "... src/states/main_menu_state.s"
	@echo "... src/states/new_hero_state.o"
	@echo "... src/states/new_hero_state.i"
	@echo "... src/states/new_hero_state.s"
	@echo "... src/states/playing_state.o"
	@echo "... src/states/playing_state.i"
	@echo "... src/states/playing_state.s"
	@echo "... src/states/select_hero_state.o"
	@echo "... src/states/select_hero_state.i"
	@echo "... src/states/select_hero_state.s"
	@echo "... src/states/show_savegame_state.o"
	@echo "... src/states/show_savegame_state.i"
	@echo "... src/states/show_savegame_state.s"
	@echo "... src/storm/stormlib.o"
	@echo "... src/storm/stormlib.i"
	@echo "... src/storm/stormlib.s"
	@echo "... src/video.o"
	@echo "... src/video.i"
	@echo "... src/video.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

